### ISSUE TITLE
drawImage is not a function

### ISSUE THREAD

**Issue by qigongBea** [dustmop/rasterjs#4]
My code: 
```
//ui_func.js
23   let img = drawObj.loadImage(
24     this.context[0],
25     this.context[1],
26     this.context[2]
27   );
28   drawObj.drawImage(img);
```
Error:
ui_func.js:28  Uncaught TypeError: drawObj.drawImage is not a function
    at UI.draw (ui_func.js:28:13)
    at draw (main.js:28:11)
    at Executor._execNextFrame (executor.js:64:7)
    at eval (executor.js:30:49)
    at renderIt (webgl_display.js:376:22)
    at WebGLDisplay._beginLoop (webgl_display.js:401:5)
    at eval (webgl_display.js:327:12)
    at eval (webgl_display.js:308:7)

**Comment by dustmop** [comment]
Sorry about that, the method `drawImage` has been replaced by `paste`. I will update the docs to describe this new function. Try this code instead:

```
//ui_func.js
23   let img = drawObj.loadImage(
24     this.context[0],
25     this.context[1],
26     this.context[2]
27   );
28   drawObj.paste(img);
```

**Comment by qigongBea** [comment]
你好！我已经收到了你的邮件。我会尽快回复。Hello!I have received your email. I'll reply at fast i can.My Bilibili and Gamejolt account.不要回复这封邮件。它只是一个自动回复。Dont reply this email.It just a auto-reply.
